### ISSUE TITLE
[ Error ] on run-midi command

### ISSUE THREAD

**Issue by TerakoyaAcademia** [cifkao/groove2groove#17]
Hi. Thank you for sharing your code.
I run your code as you said and use the below command, replacing the $LOGDIR with the model directory.
However, I got this error

Replace $LOGDIR with the model directory, containing the model.yaml configuration file (e.g. one of the directories under experiments).

To run the trained model on a single pair of MIDI files, use the run-midi command, e.g.:

```
python -m groove2groove.models.roll2seq_style_transfer --logdir $LOGDIR run-midi --sample home/project/Desktop/Groove2groove/groove2groove/experiments/v01_drums_vel/v01_drums_vel/latest_checkpoint --softmax-temperature 0.6 content.mid style.mid output.mid
```

When i run this command, the following error occured.
`OSError: no MTrk header at start of track`

![errorlog](https://user-images.githubusercontent.com/85092129/141293412-a2d33772-c743-4fff-8c45-9be0b44ea3cf.png)

**Comment by cifkao** [comment]
Your command looks incorrect – you are passing the path to your checkpoint as an argument and it's probably being interpreted as a MIDI file, hence the error. Just remove the path to the checkpoint and you should be fine.

**Comment by TerakoyaAcademia** [comment]
@cifkao, I have followed all the steps in the main run file. I would like to list out the steps that i have performed during the running process.
1) Created a conda environment (Pip env not done as it is mentioned inside the environment.yml file)
2) Installed the package with (pip install './code[gpu]')
3) We went to synth folder and ran the 4 commands (download.sh, train, val and test)
4) After the above commands were finished, we ran the following command
` python -m groove2groove.models.roll2seq_style_transfer --logdir $LOGDIR run-midi --sample --softmax-temperature 0.6 <inputfile1>.mid <inputfile2>.mid output.mid`

Not sure what to run in sequence, After running the above command i got the following error: 
![Screenshot from 2021-11-12 11-19-50](https://user-images.githubusercontent.com/85092129/141415452-4c549aac-9e19-481c-b248-1d69507371ec.png)

**Comment by cifkao** [comment]
Have you set `$LOGDIR` to your model directory? E.g.:
```bash
LOGDIR=/path/to/v01_drums_vel
```

**Comment by cifkao** [comment]
Also, have you extracted the checkpoint to that directory? The directory specified here should contain the files `latest_checkpoint`, `latest.ckpt-24361.data-00000-of-00001` etc.

**Comment by cifkao** [comment]
By the way, you do not need to prepare the training dataset if you are not training a model.

**Comment by TerakoyaAcademia** [comment]
@cifkao, I was providing wrong checkpoint filename. Now it is working. 
Thanks :)

**Comment by TerakoyaAcademia** [comment]
@cifkao, Can you help me on how can i implement this idea in my web app interface as you did on the supplementary website demo?
