### ISSUE TITLE
[ Error ] Run trained model.

### ISSUE THREAD

**Issue by moonsh** [cifkao/groove2groove#9]
Hi. Thank you for sharing your code.
I run your code as you said and use the below command, replacing the $LOGDIR with the model directory. 
However, I got this error 

**anaconda3/envs/groove2groove/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1534, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.**

Replace $LOGDIR with the model directory, containing the model.yaml configuration file (e.g. one of the directories under experiments).

To run the trained model on a single pair of MIDI files, use the run-midi command, e.g.:

python -m groove2groove.models.roll2seq_style_transfer --logdir $LOGDIR run-midi \
    --sample --softmax-temperature 0.6 \
    content.mid style.mid output.mid

**Comment by cifkao** [comment]
Hi, I have two questions:
1. Is there actually a checkpoint in your model directory? I.e. have you trained one and is it saved?
2. Are you using TF 1.12?

**Comment by moonsh** [comment]
Ah, yes. I found that the detailed explanation is in the sub-folder. I started training. Thank you!.
